# To be run inside the VM if you weren't able to download the image from Google Drive
sudo apt update && sudo apt -y upgrade
sudo apt -y install python3 python3-pip libusb1.0 wget
python3 -m pip install pyusb
